import { Box, Container, IconButton, Typography } from "@mui/material"
import VaccinesIcon from '@mui/icons-material/Vaccines';
const ButtonBar = ()=>{
    return(
        <Box
        sx={{
           
            width:{
                xs:"100%",
                sm:"100",
                md:"100%",
                lg:"100%",
                xl:"100%"
            },
   
            display:"flex",
            justifyContent:"center"
        }}>
        <Box
        sx={{
            width:{
                xs:"100%",
                sm:"84",
                md:"84%",
                lg:"84%",
                xl:"84%"
            },
            height:{
                xs:"18vh",
                sm:"18vh",
                md:"18vh",
                lg:"18px",
                xl:"18px"
            },
         //   height:"16vh",
            background:"#FFF",
            display:'flex',
            alignItems:'center',
            justifyContent:'space-between'
          
        }}>
            <Box
             sx={{
                display:"flex",
                flexDirection:"row",
                paddingLeft:'20px',
                width:{
                    xs:"276px",
                    sm:"280px",
                    md:"290px",
                    lg:"300px",
                    xl:"3108px"
                },
            }}>
               <IconButton 
            sx={{
                color:"#fff",
                background:"#ff4f84",
                width:"30%"
            }}>
            <VaccinesIcon/>
            </IconButton>
                <Container
               
               >
           
                    <Typography
                    sx={{
                        color:'blue',
                        fontSize:{
                            xs:"8px",
                            sm:"9px",
                            md:"10px",
                            lg:"12px",
                            xl:"13px"
                        }
                    }}>
                        Lorem ipsum Doctor
                    </Typography>
                    <Typography
                     sx={{
                        color:'#000',
                        fontSize:{
                            xs:"3px",
                            sm:"4px",
                            md:"6px",
                            lg:"7px",
                            xl:"8px"
                        }
                    }}>
                        qsdfezfzefzefzefzeefz
                    </Typography>
                    <Typography
                         sx={{
                            color:'#000',
                            fontSize:{
                                xs:"3px",
                                sm:"4px",
                                md:"6px",
                                lg:"7px",
                                xl:"8px"
                            }
                        }}>
                        qsdfezfzefzefzefzee
                    </Typography>
                    <Typography
                         sx={{
                            color:'#000',
                            fontSize:{
                                xs:"3px",
                                sm:"4px",
                                md:"6px",
                                lg:"7px",
                                xl:"8px"
                            }
                        }}>
                        qsdfezfzefzefzefzeefz
                    </Typography>
                </Container>
            </Box>
            <Box
             sx={{
                display:"flex",
                flexDirection:"row",
                paddingLeft:'20px',
                width:{
                    xs:"276px",
                    sm:"280px",
                    md:"290px",
                    lg:"300px",
                    xl:"310px"
                },
            }}>
               <IconButton 
            sx={{
                color:"#fff",
                background:"#ff4f84",
                width:"30%"
            }}>
            <VaccinesIcon/>
            </IconButton>
                <Container
               
               >
           
                    <Typography
                    sx={{
                        color:'blue',
                        fontSize:{
                            xs:"8px",
                            sm:"9px",
                            md:"10px",
                            lg:"12px",
                            xl:"13px"
                        }
                    }}>
                        Lorem ipsum Doctor
                    </Typography>
                    <Typography
                     sx={{
                        color:'#000',
                        fontSize:{
                            xs:"3px",
                            sm:"4px",
                            md:"6px",
                            lg:"7px",
                            xl:"8px"
                        }
                    }}>
                        qsdfezfzefzefzefzeefz
                    </Typography>
                    <Typography
                         sx={{
                            color:'#000',
                            fontSize:{
                                xs:"3px",
                                sm:"4px",
                                md:"6px",
                                lg:"7px",
                                xl:"8px"
                            }
                        }}>
                        qsdfezfzefzefzefzee
                    </Typography>
                    <Typography
                         sx={{
                            color:'#000',
                            fontSize:{
                                xs:"3px",
                                sm:"4px",
                                md:"6px",
                                lg:"7px",
                                xl:"8px"
                            }
                        }}>
                        qsdfezfzefzefzefzeefz
                    </Typography>
                </Container>
            </Box>
            <Box
             sx={{
                display:"flex",
                flexDirection:"row",
                paddingLeft:'20px',
                width:{
                    xs:"276px",
                    sm:"280px",
                    md:"290px",
                    lg:"300px",
                    xl:"310px"
                },
            }}>
               <IconButton 
            sx={{
                color:"#fff",
                background:"#ff4f84",
                width:"30%"
            }}>
            <VaccinesIcon/>
            </IconButton>
                <Container
               
               >
           
                    <Typography
                    sx={{
                        color:'blue',
                        fontSize:{
                            xs:"8px",
                            sm:"9px",
                            md:"10px",
                            lg:"12px",
                            xl:"13px"
                        }
                    }}>
                        Lorem ipsum Doctor
                    </Typography>
                    <Typography
                     sx={{
                        color:'#000',
                        fontSize:{
                            xs:"3px",
                            sm:"4px",
                            md:"6px",
                            lg:"7px",
                            xl:"8px"
                        }
                    }}>
                        qsdfezfzefzefzefzeefz
                    </Typography>
                    <Typography
                         sx={{
                            color:'#000',
                            fontSize:{
                                xs:"3px",
                                sm:"4px",
                                md:"6px",
                                lg:"7px",
                                xl:"8px"
                            }
                        }}>
                        qsdfezfzefzefzefzee
                    </Typography>
                    <Typography
                         sx={{
                            color:'#000',
                            fontSize:{
                                xs:"3px",
                                sm:"4px",
                                md:"6px",
                                lg:"7px",
                                xl:"8px"
                            }
                        }}>
                        qsdfezfzefzefzefzeefz
                    </Typography>
                </Container>
            </Box>
        </Box>
        </Box>
       
    )
}

export default ButtonBar